# Generated by Django 5.1.15 on 2026-06-14 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('chat_message', 'Chat Message'), ('proposal', 'Proposal'), ('invitation', 'Invitation'), ('contract', 'Contract'), ('submission', 'Submission'), ('payment', 'Payment'), ('ticket', 'Ticket'), ('admin_broadcast', 'Admin')], max_length=20)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('deep_link', models.CharField(blank=True, max_length=200)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed', models.BooleanField(default=False)),
                ('pushed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'read_at', '-created_at'], name='notificatio_user_id_554261_idx')],
            },
        ),
    ]
