# Generated by Django 5.1.15 on 2026-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerlanguage',
            name='proficiency',
            field=models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('native', 'Native')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='expertise_level',
            field=models.CharField(blank=True, choices=[('entry', 'Entry'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=14),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='visibility',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=8),
        ),
        migrations.AlterField(
            model_name='workerskill',
            name='efficiency',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=12),
        ),
    ]
