# Generated by Django 5.1.15 on 2026-06-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_workerprofile_is_verified_idverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='offline_reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
