# Generated by Django 5.1.15 on 2026-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_workerprofile_offline_reminder_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='cover_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('link', 'Link')], default='image', max_length=8),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
