# Generated by Django 5.1.15 on 2026-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_workerprofile_publish_default_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress employers post ID (data migration).', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress freelancers post ID (data migration).', null=True, unique=True),
        ),
    ]
