# Generated by Django 5.1.15 on 2026-06-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_employerprofile_legacy_id_workerprofile_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress wt_portfolio post ID (data migration).', null=True, unique=True),
        ),
    ]
