# Generated by Django 5.1.15 on 2026-06-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='report',
            new_name='core_report_kind_c11a88_idx',
            old_name='core_report_kind_obj_idx',
        ),
        migrations.RenameIndex(
            model_name='report',
            new_name='core_report_status_2f6592_idx',
            old_name='core_report_status_idx',
        ),
    ]
