# Generated by Django 5.1.15 on 2026-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_core_report_kind_obj_idx_core_report_kind_c11a88_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress reports post ID (data migration).', null=True, unique=True),
        ),
    ]
