# Generated by Django 5.1.15 on 2026-06-15 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('hero', 'Hero'), ('cards', 'Feature cards'), ('categories', 'Category cards'), ('steps', 'How-it-works steps'), ('cta', 'Call to action')], max_length=12)),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('subheading', models.TextField(blank=True)),
                ('cta_primary_label', models.CharField(blank=True, max_length=60)),
                ('cta_primary_link', models.CharField(blank=True, max_length=120)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=60)),
                ('cta_secondary_link', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(blank=True, max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=240)),
                ('link', models.CharField(blank=True, max_length=120)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cms.landingsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
