# Generated by Django 5.1.15 on 2026-06-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_contentpage_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, default='support@shoglonline.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='+20 123 456 7890', max_length=40)),
                ('contact_address', models.CharField(blank=True, default='القاهرة، مصر', max_length=200)),
                ('app_store_url', models.URLField(blank=True, default='https://apps.apple.com/app/shoglonline')),
                ('google_play_url', models.URLField(blank=True, default='https://play.google.com/store/apps/details?id=com.shoglonline')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com/shoglonline')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com/shoglonline')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com/shoglonline')),
                ('youtube_url', models.URLField(blank=True, default='https://youtube.com/@shoglonline')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com/company/shoglonline')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
