# Generated by Django 5.1.15 on 2026-06-29 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(blank=True, max_length=120)),
                ('legacy_plan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('jobs_quota', models.PositiveIntegerField(default=0)),
                ('featured_jobs_quota', models.PositiveIntegerField(default=0)),
                ('duration_type', models.CharField(blank=True, max_length=20)),
                ('has_banner', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
