# Generated by Django 5.1.15 on 2026-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_icon_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress term_id (service_categories/project_cat; data migration).', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress term_id (skills taxonomy; data migration).', null=True, unique=True),
        ),
    ]
