# Generated by Django 5.1.15 on 2026-06-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_category_legacy_id_skill_legacy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=160, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=160, unique=True),
        ),
    ]
