# Generated by Django 5.1.15 on 2026-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active_mode',
            field=models.CharField(blank=True, choices=[('find_job', 'Find a job'), ('find_worker', 'Hire now')], help_text='Pure view preference — NEVER used for authorization (FR-MODE-4)', max_length=12),
        ),
    ]
