# Generated by Django 5.1.15 on 2026-06-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emaillogincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillogincode',
            name='code',
            field=models.CharField(max_length=16),
        ),
    ]
