# Generated by Django 5.1.15 on 2026-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_emaillogincode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress wp_users.ID (data migration); null for app-created users.', null=True, unique=True),
        ),
    ]
