# Generated by Django 5.1.15 on 2026-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='frozen_prev_status',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='job',
            name='frozen_prev_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='proposal',
            name='frozen_prev_status',
            field=models.CharField(blank=True, default='', max_length=18),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='sent', max_length=12),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('suspended', 'Suspended')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Pending Approval'), ('submitted', 'Submitted'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn'), ('suspended', 'Suspended')], default='submitted', max_length=18),
        ),
    ]
