# Generated by Django 5.1.15 on 2026-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_expected_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress projects post ID (data migration).', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress proposals post ID (data migration).', null=True, unique=True),
        ),
    ]
