# Generated by Django 5.1.15 on 2026-06-14 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=180, unique=True)),
                ('description', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_days', models.PositiveSmallIntegerField(default=7)),
                ('cover_image', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('live', 'Live'), ('paused', 'Paused'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=16)),
                ('reject_reason', models.TextField(blank=True)),
                ('favorites_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='catalog.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_services', to='catalog.category')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_days', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='gigs.service')),
            ],
        ),
        migrations.CreateModel(
            name='BuyingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('files', models.JSONField(blank=True, default=list)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_days', models.PositiveSmallIntegerField(default=7)),
                ('status', models.CharField(choices=[('pending', 'بانتظار قبول المستقل'), ('accepted', 'مقبول — أُنشئ عقد'), ('rejected', 'مرفوض'), ('cancelled', 'ألغاه المشتري')], default='pending', max_length=10)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buying_requests', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='gigs.service')),
                ('addons', models.ManyToManyField(blank=True, related_name='requests', to='gigs.serviceaddon')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='gigs.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'category', '-published_at'], name='gigs_servic_status_a0d014_idx'),
        ),
        migrations.AddConstraint(
            model_name='buyingrequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='servicefavorite',
            constraint=models.UniqueConstraint(fields=('user', 'service'), name='uniq_service_favorite'),
        ),
    ]
