# Generated by Django 5.1.15 on 2026-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_alter_buyingrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='frozen_prev_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
