# Generated by Django 5.1.15 on 2026-06-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0006_favorite'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favorite',
            new_name='gigs_favori_user_id_439f5c_idx',
            old_name='gigs_fav_user_kind_idx',
        ),
    ]
