# Generated by Django 5.1.15 on 2026-06-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0008_service_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress micro-services post ID (data migration).', null=True, unique=True),
        ),
    ]
