# Generated by Django 5.1.15 on 2026-06-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0009_service_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceaddon',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress addons-services post ID (data migration).', null=True, unique=True),
        ),
    ]
