# Generated by Django 5.1.15 on 2026-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress reviews post ID (data migration).', null=True, unique=True),
        ),
    ]
