# Generated by Django 5.1.15 on 2026-06-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='firestore_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
