# Generated by Django 5.1.15 on 2026-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_firestore_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='frozen_prev_status',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
