# Generated by Django 5.1.15 on 2026-07-01 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatreport'),
        ('contracts', '0005_submission_legacy_id'),
        ('gigs', '0011_service_cover_attachment'),
        ('jobs', '0006_job_legacy_id_proposal_legacy_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gigs.service'),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('context_type', 'service')), fields=('user_a', 'user_b', 'service'), name='uniq_service_conversation'),
        ),
    ]
