# Generated by Django 5.1.15 on 2026-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicerequest',
            name='period_type',
            field=models.CharField(choices=[('week', 'Week'), ('month', 'Month')], default='month', max_length=6),
        ),
        migrations.AlterField(
            model_name='invoicerequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='requested', max_length=10),
        ),
    ]
