# Generated by Django 5.1.15 on 2026-06-26 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_status_alter_submission_status_and_more'),
        ('invoices', '0002_alter_invoicerequest_period_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='contracts.contract'),
        ),
    ]
