# Generated by Django 5.1.15 on 2026-06-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal_hold', 'Withdrawal Hold'), ('withdrawal_paid', 'Withdrawal Paid'), ('withdrawal_reversed', 'Withdrawal Reversed'), ('bid_purchase', 'Bid Purchase'), ('contract_hold', 'Contract Hold'), ('contract_release', 'Contract Release'), ('earning', 'Earning'), ('commission', 'Commission'), ('affiliate', 'Affiliate'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
