# Generated by Django 5.1.15 on 2026-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payoutmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress wt_payouts_history.id (data migration).', null=True, unique=True),
        ),
    ]
