# Generated by Django 5.1.15 on 2026-06-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.SmallIntegerField()),
                ('reason', models.CharField(choices=[('signup_grant', 'Signup Grant'), ('monthly_grant', 'Monthly Grant'), ('purchase', 'Purchase'), ('consume', 'Consume'), ('refund_moderation', 'Refund Moderation'), ('refund_job_closed', 'Refund Job Closed'), ('admin_adjust', 'Admin Adjust')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BidPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('bids_count', models.PositiveSmallIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['bids_count'],
            },
        ),
    ]
