# Generated by Django 5.1.15 on 2026-06-12 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bids', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bidledger',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bid_entries', to='jobs.proposal'),
        ),
        migrations.AddField(
            model_name='bidledger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bid_ledger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bidledger',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bids.bidplan'),
        ),
        migrations.AddIndex(
            model_name='bidledger',
            index=models.Index(fields=['user', '-created_at'], name='bids_bidled_user_id_e21bc9_idx'),
        ),
    ]
