# Generated by Django 5.1.15 on 2026-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('solved', 'Solved'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
