# Generated by Django 5.1.15 on 2026-06-17 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='on_hold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='on_hold_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('pending', 'Pending'), ('on_hold', 'On-Hold'), ('solved', 'Solved'), ('closed', 'Closed')], default='open', max_length=10),
        ),
    ]
