# Generated by Django 5.1.15 on 2026-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_on_hold_at_ticket_on_hold_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress emd_ticket post ID (data migration).', null=True, unique=True),
        ),
    ]
