# Generated by Django 5.1.15 on 2026-06-14 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('scope', models.TextField(blank=True)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('worker_earning', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending_funding', 'بانتظار التمويل'), ('active', 'نشط'), ('delivered', 'تم التسليم'), ('completed', 'مكتمل'), ('disputed', 'متنازع عليه'), ('cancelled', 'ملغى')], default='pending_funding', max_length=16)),
                ('funding_deadline', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('warranty_ends_at', models.DateTimeField(blank=True, null=True)),
                ('funds_released', models.BooleanField(default=False)),
                ('cancel_reason', models.CharField(blank=True, max_length=300)),
                ('dispute_ticket_ref', models.CharField(blank=True, max_length=64)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('overdue_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancel_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_employer', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.job')),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.proposal')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts_as_worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('files', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('open', 'قيد المراجعة'), ('accepted', 'مقبول'), ('rejected', 'مرفوض')], default='open', max_length=8)),
                ('reject_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UpdateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_deadline', models.DateField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'بانتظار الرد'), ('pending_funding', 'بانتظار تمويل الفرق'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('cancelled', 'ملغى')], default='pending', max_length=16)),
                ('reject_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_requests', to='contracts.contract')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status', '-created_at'], name='contracts_c_status_e5aa9f_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['warranty_ends_at'], name='contracts_c_warrant_1fbc22_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['funding_deadline'], name='contracts_c_funding_41b0ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('worker', models.F('employer')), _negated=True), name='contract_no_self_dealing'),
        ),
    ]
