# Generated by Django 5.1.15 on 2026-06-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
        ('gigs', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='buying_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='gigs.buyingrequest'),
        ),
        migrations.AddField(
            model_name='contract',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='gigs.service'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.proposal'),
        ),
    ]
