# Generated by Django 5.1.15 on 2026-06-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_buying_request_contract_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending_funding', 'Pending funding'), ('active', 'Active'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending_funding', max_length=16),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='open', max_length=8),
        ),
        migrations.AlterField(
            model_name='updaterequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('pending_funding', 'Pending funding'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
