# Generated by Django 5.1.15 on 2026-06-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_status_alter_submission_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress wt_earnings.id (data migration).', null=True, unique=True),
        ),
    ]
