# Generated by Django 5.1.15 on 2026-06-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='legacy_id',
            field=models.BigIntegerField(blank=True, help_text='WordPress wt-milestone post ID (data migration).', null=True, unique=True),
        ),
    ]
